# version: '3.9'

services:
  springboot:
    build:
      context: ./back-end/patient-care
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/patient_care?useSSL=false&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT=org.hibernate.dialect.MySQL8Dialect
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE:-dev}
      - RASA_URL=http://rasa:5005/webhooks/rest/webhook
    networks:
      - app-network
    env_file:
      - .env
    entrypoint: [ "./wait-for-it.sh", "mysql:3306", "--", "java", "-jar", "/app/app.jar" ]

  fastapi:
    build:
      context: ./rasa_env/rasa_env/fastapi_service
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    networks:
      - app-network

  mysql:
    image: mysql:8.0.32
    container_name: mysql_container
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=patient_care
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-network
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 30s
      retries: 3
      start_period: 10s
      timeout: 5s

  rasa:
    image: rasa/rasa:3.0.0-full
    ports:
      - "5005:5005"
    networks:
      - app-network
    volumes:
      - ./rasa_env:/app
    command: [ "rasa", "run", "--enable-api", "--cors", "*" ]

  angular:
    build:
      context: ./front-end/healthcare-dashboard
      dockerfile: Dockerfile
    ports:
      - "4200:80"
    environment:
      - API_BASE_URL=http://springboot:8080
    networks:
      - app-network

volumes:
  db_data:


networks:
  app-network:
    driver: bridge
